name: division
description: Simple to use yet powerfull style widgets with syntax inspired by CSS.
version: 0.8.6
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
